import { DEFAULT_PARAMS, type Params } from "./types";

export interface Preset {
  id: string;
  name: string;
  note: string;
  params: Params;
}

export const PRESETS: Preset[] = [
  {
    id: "yosemite",
    name: "Yosemite",
    note: "High noon granite",
    params: {
      ...DEFAULT_PARAMS,
      flow: 0.82,
      width: 0.46,
      drop: 0.92,
      wind: 0.08,
      turbulence: 0.36,
      mist: 0.5,
      foam: 0.7,
      rainbow: 0.22,
      timeOfDay: 12.4,
      season: 0.28,
      weather: 0.05,
      vegetation: 0.62,
      rockWarmth: 0.32,
      seed: 11,
    },
  },
  {
    id: "golden",
    name: "Golden Hour",
    note: "Warm stone, long light",
    params: { ...DEFAULT_PARAMS },
  },
  {
    id: "iceland",
    name: "Iceland",
    note: "Wind, mist, basalt",
    params: {
      ...DEFAULT_PARAMS,
      flow: 0.88,
      width: 0.78,
      drop: 0.7,
      wind: 0.62,
      turbulence: 0.7,
      mist: 0.86,
      foam: 0.8,
      rainbow: 0.55,
      timeOfDay: 8.2,
      season: 0.18,
      weather: 0.48,
      vegetation: 0.22,
      rockWarmth: 0.12,
      seed: 23,
    },
  },
  {
    id: "shrine",
    name: "Hidden Shrine",
    note: "Narrow, moss, dawn",
    params: {
      ...DEFAULT_PARAMS,
      flow: 0.38,
      width: 0.22,
      drop: 0.64,
      wind: 0.04,
      turbulence: 0.28,
      mist: 0.42,
      foam: 0.45,
      rainbow: 0.18,
      timeOfDay: 6.5,
      season: 0.08,
      weather: 0.12,
      vegetation: 0.95,
      rockWarmth: 0.4,
      seed: 41,
    },
  },
  {
    id: "autumn",
    name: "Autumn Veil",
    note: "Copper canopy",
    params: {
      ...DEFAULT_PARAMS,
      flow: 0.58,
      width: 0.4,
      drop: 0.74,
      wind: 0.22,
      turbulence: 0.38,
      mist: 0.4,
      foam: 0.55,
      rainbow: 0.12,
      timeOfDay: 16.8,
      season: 0.54,
      weather: 0.16,
      vegetation: 0.88,
      rockWarmth: 0.62,
      seed: 5,
    },
  },
  {
    id: "moonwell",
    name: "Moonwell",
    note: "Night pool, fireflies",
    params: {
      ...DEFAULT_PARAMS,
      flow: 0.44,
      width: 0.34,
      drop: 0.68,
      wind: 0.06,
      turbulence: 0.32,
      mist: 0.7,
      foam: 0.5,
      rainbow: 0,
      timeOfDay: 22.4,
      season: 0.22,
      weather: 0.08,
      vegetation: 0.7,
      rockWarmth: 0.28,
      seed: 17,
      wildlife: true,
    },
  },
  {
    id: "monsoon",
    name: "Monsoon",
    note: "Full roar, rain",
    params: {
      ...DEFAULT_PARAMS,
      flow: 0.96,
      width: 0.86,
      drop: 0.8,
      wind: 0.34,
      turbulence: 0.78,
      mist: 0.8,
      foam: 0.92,
      rainbow: 0.08,
      timeOfDay: 14.2,
      season: 0.32,
      weather: 0.88,
      vegetation: 0.8,
      rockWarmth: 0.36,
      seed: 29,
    },
  },
  {
    id: "frozen",
    name: "Frozen",
    note: "Ice lip, still air",
    params: {
      ...DEFAULT_PARAMS,
      flow: 0.26,
      width: 0.3,
      drop: 0.72,
      wind: 0.18,
      turbulence: 0.22,
      mist: 0.34,
      foam: 0.28,
      rainbow: 0,
      timeOfDay: 9.1,
      season: 0.78,
      weather: 0.28,
      vegetation: 0.18,
      rockWarmth: 0.08,
      seed: 3,
    },
  },
];
